#!/usr/bin/with-contenv bash

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
DB_HOST=${DB_HOST:-trinitycore-db}
DB_PORT=${DB_PORT:-3306}
DB_USER=${DB_USER:-trinity}
DB_PASS=${DB_PASS:-trinity}
DB_ROOT_USER=${DB_ROOT_USER:-root}
DB_ROOT_PASS=${DB_ROOT_PASS:-root}
DB_TIMEOUT=${DB_TIMEOUT:-30}

dbcmd="mysql -h ${DB_HOST} -P ${DB_PORT} -u "${DB_USER}" "-p${DB_PASS}""
echo $dbcmd
echo "Waiting ${DB_TIMEOUT}s for database to be ready..."
counter=1
while ! ${dbcmd} -e "show databases;" > /dev/null 2>&1; do
  sleep 1
  counter=$((counter + 1))
  if [ ${counter} -gt ${DB_TIMEOUT} ]; then
    >&2 echo "ERROR: Failed to connect to database on $DB_HOST"
    exit 1
  fi;
done
echo "Database ready!"

mkdir -p /data

# extract and copy over dbc and map files
if [ ! -d "/data/dbc" ]; then
	echo "**** DBC and map files not found - extracting ****"
	cd /game
	/app/server/bin/mapextractor
	cp -r dbc maps /data/
fi

if [ ! -d "/data/vmaps" ]; then
	echo "**** visual maps (vmaps) not found - extracting ****"
	cd /game
	/app/server/bin/vmap4extractor
	mkdir -p vmaps
	/app/server/bin/vmap4assembler Buildings vmaps
	cp -r vmaps /data/
fi

if [ ! -d "/data/mmaps" ]; then
	echo "**** mmaps not found - extracting: THIS COULD TAKE A WHILE ****"
	cd /game
	mkdir mmaps
	/app/server/bin/mmaps_generator
	cp -r mmaps /data/
fi

if [ ! -f "/app/server/etc/worldserver.conf" ]; then
        # Add in solocraft config
        cat /defaults/solocraft.conf >> /app/server/etc/worldserver.conf.dist

	cp /app/server/etc/worldserver.conf.dist /app/server/etc/worldserver.conf
	# Set DataDir to the proper location
	sed -i 's|DataDir = "."|DataDir = "/data"|g' /app/server/etc/worldserver.conf

	# Fix database connection info
	sed -i 's|127.0.0.1;3306;trinity;trinity|trinitycore-db;3306;trinity;trinity|g' /app/server/etc/worldserver.conf
fi

if [ ! -f "/app/server/etc/authserver.conf" ]; then
	cp /app/server/etc/authserver.conf.dist /app/server/etc/authserver.conf

	# Fix database connection info
	sed -i 's|127.0.0.1;3306;trinity;trinity|trinitycore-db;3306;trinity;trinity|g' /app/server/etc/authserver.conf
fi

# Initial setup required for database
mysql -u root -p${MYSQL_ROOT_PASSWORD} --host trinitycore-db < /defaults/db_setup.sql

# Move any TDB seed files into the bin directory for seeding
cp /data/TDB_*sql /app/server/bin/

# Update the database
cd /app/server/bin && ./worldserver --update-databases-only

# Seed DB with bot files
mysql -u root -p${MYSQL_ROOT_PASSWORD} --host trinitycore-db world < /trinity-bots/last/SQL/1_world_bot_appearance.sql
mysql -u root -p${MYSQL_ROOT_PASSWORD} --host trinitycore-db world < /trinity-bots/last/SQL/2_world_bot_extras.sql
mysql -u root -p${MYSQL_ROOT_PASSWORD} --host trinitycore-db world < /trinity-bots/last/SQL/3_world_bots.sql
mysql -u root -p${MYSQL_ROOT_PASSWORD} --host trinitycore-db world < /trinity-bots/last/SQL/4_world_generate_bot_equips.sql
mysql -u root -p${MYSQL_ROOT_PASSWORD} --host trinitycore-db characters < /trinity-bots/last/SQL/characters_bots.sql

# permissions
# chown -R abc:abc \
	# /app/server
